site_name: Calculation Docs

theme:
  name: "material"

plugins:
#  Thêm cái mục này vào để nó fetch cái docstrings trong code
  - mkdocstrings

nav:
#  Tên section: Tên file chứa nội dung section
  - Calculation Docs: index.md
  - Tutorials: tutorials.md
  - How-to Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md
